env: test5
spring:
    application:
      name: order
    datasource:
      username: root
      password: 19970807
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/SpringCloud_sell?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    jpa:
      show-sql: true
girl:
  name: GGGGGGG1
  age: 12
